### ISSUE TITLE
looking good!

### ISSUE THREAD

**Issue by Gingeropolous** [Monero-Monitor/monero-wallet-chrome#6]
The new wallet behavior is perfect. the Confirm and then info that the transfer went through.

I noticed though that the monero:address behavior might not be working. When I clicked on your donate link, my browser just went to monero:youraddresshere . I assume it should automatically load the wallet with the to field already filled out? I didn't restart my chrome.. maybe thats necessary.

also, was the simplewallet script part of this release?  I didn't see it or encounter it during my install.

**Comment by bigreddmachine** [comment]
You're absolutely right about the link behavior. It has been working in tabs for a while (you can try it out on the [Monero development team donations page](https://getmonero.org/getting-started/donate/)) but not in links in the extension itself. It was something I had meant to do but hadn't. I took care of it this morning here: c914c6abadbe9850a7cf92557a4152d9eee50aca (which was after the tagged release you got). It'll be in the beta release :)

The scripts aren't there yet. I've just about finished the unix script - just need to decide if I want two scripts, one for local wallet and one for remote wallets, or one script that handles both. Two scripts is easier for me, but one is probably easier for everyone else haha. And then I still need to test my windows script. I basically translated bash (unix) to batch (windows) but haven't tested it. Gonna try to do that tomorrow morning.

Once I get them finalized, I'll make a startup page that will walk new users through setup. If you want to try one out, they're in the repo in /scripts, but it's probably best to wait to try them until i test them a bit more.

**Comment by bigreddmachine** [comment]
Thanks again for the feedback - all of this should be resolved as of 7549cc550f53cc1756978e5ca487b76c9f8b096c. Closing!
