### ISSUE TITLE
Transactions hashes do not match real ones

### ISSUE THREAD

**Issue by Stevus24654** [Monero-Monitor/monero-wallet-chrome#7]
Hello,

I have set up the extension and all works fine, but the transaction hashes are not "real" hashes even though the # and amounts are correct
Any ideas ?

Thank you

**Comment by bigreddmachine** [comment]
@Stevus24654 - @kenshi84 submitted a PR to fix this today. I'll review it asap and get a new Chrome Store release once done. Thanks for the issue, and for patience... December was a very busy work month for me and I haven't had a lot of time to look into this.

And thanks kenshi84!

**Comment by kenshi84** [comment]
It's my very first time to play with Chrome Extension and also to use wallet RPC, and I'm glad to know how simple and easy it is to implement something like this! Really appreciate your work :)

**Comment by bigreddmachine** [comment]
Fixed with PR #9 

Will be fixed in next Chrome Store release, BUT can't do a release until the next Monero Core point release... the new RPC authentication isn't included in a point release yet, and I want to keep the Chrome Store version of this compatible with those releases.

**Comment by kenshi84** [comment]
Yes, we'll have to wait for a while before the next point release. I just wanted to make the extension work with the latest master which I use regularly.
